version: '3'

services:
  node-app:
    build: ./app
    container_name: node_app_demo
    ports:
      - 8080:8080
  reverse-proxy:
    image: nginx:1.23.4
    container_name: reverse_proxy_demo
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/html
    ports:
      - 80:80
    depends_on:
      - node-app